version: '3'

volumes:
  pg_data:
  static:
  media: 

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nikita4/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media 
  frontend:
    image: nikita4/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: nikita4/kitty_nginx
    env_file: .env
    volumes:
      - static:/static
      - media:/media 
    ports:
      - 9000:80